/**
 * Ярмарка предзаказ — конфиг товаров.
 * Чтобы добавить товар: скопируйте один блок { id: ... } и заполните поля.
 * Чтобы убрать товар — удалите его блок.
 * Изображения кладите в папку yarmarket/ рядом с этим файлом.
 * sizes: [] — означает «без размеров» (для украшений, свечей и т.п.)
 */
var YARMARKET_CONFIG = {
  products: [
    {
      id: "shirt1",
      name: "Футболка «Чакры» (бежевая, радуга)",
      price: 0,
      image: "yarmarket/shirt1.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      id: "shirt2",
      name: "Футболка «Древо жизни» (бежевая)",
      price: 0,
      image: "yarmarket/shirt2.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      id: "shirt3",
      name: "Футболка «Чакры» (зелёная, жёлтая)",
      price: 0,
      image: "yarmarket/shirt3.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      id: "shirt4",
      name: "Футболка «Чакры» (зелёная, радуга)",
      price: 0,
      image: "yarmarket/shirt4.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      id: "shirt5",
      name: "Футболка «Древо жизни» (зелёная)",
      price: 0,
      image: "yarmarket/shirt5.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      id: "book",
      name: "Книга Даров",
      price: 0,
      image: "yarmarket/book.jpg",
      sizes: [],
      description: "«64 ключа к твоим суперсилам» — СветЛана.\nПервый эксклюзивный тираж, только на слёте.",
    },
    {
      id: "sunshine",
      name: "Брызги солнца",
      price: 0,
      image: "yarmarket/sunshine.jpg",
      sizes: [],
      description: "Зеркало, кристаллы, стекло.\nНатали — Breeze of Dream",
    },
    {
      id: "choker",
      name: "Чокер + серьги асимметрия",
      price: 0,
      image: "yarmarket/choker.jpg",
      sizes: [],
      description: "Натуральная замша, агаты.\nНатали — Breeze of Dream",
    },
    {
      id: "dreamcatcher3",
      name: "Ловец снов-талисман",
      price: 0,
      image: "yarmarket/dreamcatcher3.jpg",
      sizes: [],
      description: "Натуральная кожа, натуральные камни, джут, фликер.\nНатали — Breeze of Dream",
    },
    {
      id: "dreamcatcher2",
      name: "Ловец снов с музыкой ветра",
      price: 0,
      image: "yarmarket/dreamcatcher2.jpg",
      sizes: [],
      description: "Бамбук, пряжа, шерл.\nНатали — Breeze of Dream",
    },
    {
      id: "dreamcatcher",
      name: "Ловец снов «Древо»",
      price: 0,
      image: "yarmarket/dreamcatcher.jpg",
      sizes: [],
      description: "Лоза, рудракша, перо орла, джут.\nНатали — Breeze of Dream",
    },
    {
      id: "dress",
      name: "Платье Этника",
      price: 230,
      image: "yarmarket/dress.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Свободное этническое платье оверсайз из хлопка и льна с разрезами.\nДизайнер «TURIYA» — Наима",
    },
    {
      id: "kimono",
      name: "Кимоно Рассвет",
      price: 280,
      image: "yarmarket/kimono.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "Элегантное персиковое кимоно из крапивы с поясом и боковыми разрезами.\nДизайнер «TURIYA» — Наима",
    },
    {
      id: "pendant",
      name: "Кулон-талисман «Купала»",
      price: 0,
      image: "yarmarket/pendant.jpg",
      sizes: [],
      description: "Талисман со славянской тематикой в единственном экземпляре — позволит вам надолго запомнить праздник Купалы.\nВероника Сушицкая",
    },
    {
      id: "tea",
      name: "Витаминный чай лесной",
      price: 0,
      image: "yarmarket/tea.jpg",
      sizes: [],
      description: "Ароматный лесной сбор: земляника, малина, черника, смородина, сосновые пыльники, шиповник.\nТатьяна Кузнецова",
    },
    {
      id: "oils",
      name: "Масла холодного отжима",
      price: 0,
      image: "yarmarket/oils.jpg",
      sizes: [],
      description: "В ассортименте: конопляное, тыквенное, кунжутное, горчичное, льняное, подсолнечное, миндальное, из абрикосовой косточки и другие.\nТатьяна Кузнецова",
    },
    {
      id: "urbech",
      name: "Урбеч — натуральная паста из семян",
      price: 0,
      image: "yarmarket/urbech.jpg",
      sizes: [],
      description: "Полезная натуральная паста из семян. Уникальный авторский состав: кунжут–кокос–кэроб и другие.\nТатьяна Кузнецова",
    },
    {
      id: "mustard",
      name: "Горчичный порошок 🔥",
      price: 0,
      image: "yarmarket/mustard.jpg",
      sizes: [],
      description: "Очень качественный горчичный порошок — можно сделать звёздную 🌟 горчицу, помыть посуду, добавлять в майонезы и соусы.\nТатьяна Кузнецова",
    },
    {
      id: "herbs",
      name: "Витаминный сбор Здоровье 🍀",
      price: 0,
      image: "yarmarket/herbs.jpg",
      sizes: [],
      description: "Добавка к питанию от природы, жмых из 8-ми полезных трав, сухой салат — можно развести в воде и выпить, добавить в коктейли.\nТатьяна Кузнецова",
    },
    {
      id: "pendant2",
      name: "Кулон-талисман «Купала» №2",
      price: 0,
      image: "yarmarket/pendant2.jpg",
      sizes: [],
      description: "Талисман со славянской тематикой в единственном экземпляре — позволит вам надолго запомнить праздник Купалы.\nВероника Сушицкая",
    },
    {
      id: "pendant3",
      name: "Кулон-талисман «Купала» №3",
      price: 0,
      image: "yarmarket/pendant3.jpg",
      sizes: [],
      description: "Талисман со славянской тематикой в единственном экземпляре — позволит вам надолго запомнить праздник Купалы.\nВероника Сушицкая",
    },
    {
      id: "pendant4",
      name: "Кулон-талисман «Купала» №4",
      price: 0,
      image: "yarmarket/pendant4.jpg",
      sizes: [],
      description: "Талисман со славянской тематикой в единственном экземпляре — позволит вам надолго запомнить праздник Купалы.\nВероника Сушицкая",
    },
    {
      id: "pendant5",
      name: "Кулон-талисман «Купала» №5",
      price: 0,
      image: "yarmarket/pendant5.jpg",
      sizes: [],
      description: "Талисман со славянской тематикой в единственном экземпляре — позволит вам надолго запомнить праздник Купалы.\nВероника Сушицкая",
    },
    {
      id: "dress2",
      name: "Платье Ясновижу",
      price: 380,
      image: "yarmarket/dress2.jpg",
      sizes: ["XS", "S", "M", "L", "XL", "XXL"],
      description: "из крапивы с обережной вышивкой для ясного видения.\nДизайнер «TURIYA» — Наима",
    },
    {
      id: "earrings_buton",
      name: "Серьги «Бутон»",
      price: 0,
      image: "yarmarket/earrings_buton.jpg",
      sizes: [],
    },
    {
      id: "earrings_muhomor",
      name: "Серьги «Мухоморы»",
      price: 0,
      image: "yarmarket/earrings_muhomor.jpg",
      sizes: [],
    },
    {
      id: "plate_cvetok",
      name: "Тарелочка «Цветок»",
      price: 0,
      image: "yarmarket/plate_cvetok.jpg",
      sizes: [],
    },
    {
      id: "incense_med",
      name: "Подставка под благовония «Мёд»",
      price: 0,
      image: "yarmarket/incense_med.jpg",
      sizes: [],
    },
    {
      id: "piala_life",
      name: "Пиала «Цветок жизни»",
      price: 0,
      image: "yarmarket/piala_life.jpg",
      sizes: [],
    },
    {
      id: "gidrolat",
      name: "Гидролаты от ароматерапевта",
      price: 0,
      image: "yarmarket/gidrolat.jpg",
      description: "Анастасия Декевич @anastasia.dekevich",
      sizes: [],
    },
    {
      id: "aromaroller",
      name: "Аромароллер с эфирным маслом на выбор",
      price: 0,
      image: "yarmarket/aromaroller.jpg",
      description: "Анастасия Декевич @anastasia.dekevich",
      sizes: [],
    },
  ],
};
